spring:
  cloud:
    config:
      server:
        git:
          #           搜索
          search-paths: config
          # git地址 ,github太慢。这里用gitee
          uri: https://gitee.com/zsh0525/config.git
          #          修改分支 ，默认master
          default-label: master
          #          私有得配置
#          username: XXXX
#          password: XXXX

# 开发actuator端口
management:
  endpoints:
    web:
      exposure:
        incloud: "*"