server:
  port: 8081

# 日志输出
logging:
  level:
    web: trace

spring:
  application:
    name: zsh-config
  cloud:
    config:
      server:
        native:
          search-locations: ${user.dir}/config

  profiles:
    active: git # native or git,git：读取的application-git.yml


