server:
  port: 8085

spring:
  application:
    name: zsh-consumer

eureka:
  client:
    # eureka服务中心 需配置以下
    # 是否获取服务中心的信息
    fetchRegistery: true
    # 是否注册自己
    registerWithEureka: false
    # 服务中心是。由于是自己，因此与该项目的端口匹配。不设置默认访问8761端口。
    serviceUrl:
      # 负载用逗号隔开
      defaultZone: http://localhost:8083/eureka,